# -*- coding: utf-8 -*-
"""05 operaciones abreviadas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6hTbN6XjfJSNAs876r6iTGRKFm7QND-

Condicionales Abreviadas
"""

condicion = True

if condicion:
  print("Condicion Verdadera")
else:
  print("Condicion Falsa")

mensaje = "Condicion Verdadera" if condicion else "Condicion Falsa"
print(mensaje)

mensaje = condicion and "Condicion Verdadera" or "Condicion Falsa"
print(mensaje)

"""Colecciones Comprimidas"""

l = []
for i in range(10):
  l.append(i)
print(l)

l = [i for i in range(10)]
print(l)

t = tuple(i for i in range(10))
print(t)

s = {i for i in range(10)}
print(s)

d = {chr(i): i for i in range(65, 75)}
print(d)

"""Funciones Anónimas"""

def sumar(a, b):
  return a + b

print(sumar(1, 2))

m = lambda a, b: a + b
print(m(1, 2))

l.sort(key=lambda x: x % 2)
print(l)