# -*- coding: utf-8 -*-
"""06 Archivos y Excepciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJJQB9XEF9TykwD8i09mGEebSa18pouL

## Escribir un archivo
"""

with open("archivo.txt", "w") as archivo:
    archivo.write("Hola, Mundo!")

"""## Leer un archivo"""

try:
    with open("archivo.txt", "r") as archivo:
        contenido = archivo.read()
    print(contenido)
except FileNotFoundError:
    print("Error: El archivo no existe.")
finally:
    print("Proceso terminado.")